name: Commit Validations

on:
  pull_request:
    branches:
      - main

jobs:
  commit_lint:
    name: Run Commit Lint
    uses: zcode-ia/gitops-workflows/.github/workflows/commit-lint.yml@edad4257e0935309a6cdfe51d8a282cdf8c3e94e # v1.15.0
    with:
      skip_token_generation_for_tools_repository: true
